import Layout from '@theme/Layout'
import React, { useEffect, useRef, useState } from 'react'

export const PlaywrightReport = () => {
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [iframeHeight, setIframeHeight] = useState(800)

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'iframeHeight') {
        setIframeHeight(event.data.height)
      }
    }

    window.addEventListener('message', handleMessage)
    return () => window.removeEventListener('message', handleMessage)
  }, [])

  return (
    <iframe
      ref={iframeRef}
      src="/playwright-report/index.html"
      title="Playwright Report"
      style={{
        width: '100%',
        height: `${iframeHeight}px`,
        border: '1px solid var(--ifm-color-emphasis-200)',
        backgroundColor: 'var(--ifm-color-emphasis-0)',
        borderRadius: '0.5rem',
      }}
    />
  )
}

export default function PlaywrightReportPage() {
  return (
    <Layout title="Test Report">
      <div className="main-wrapper">
        <main className="margin-vert--lg container">
          <div className="row">
            <div className="col">
              <h1>Test Report</h1>
              <p>
                This is the last test report for LTF Engine. Skipped tests are the next planned
                features. It is generated by <a href="https://playwright.dev/">Playwright</a>.
              </p>
              <PlaywrightReport />
            </div>
          </div>
        </main>
      </div>
    </Layout>
  )
}
