const {
  TEST_NOTION_TOKEN,
  TEST_NOTION_TABLE_1_ID,
  TEST_NOTION_TABLE_2_ID,
  TEST_NOTION_TABLE_3_ID,
  TEST_NOTION_TABLE_FILES_ID,
  TEST_PAPPERS_API_KEY,
  TEST_QONTO_ORGANISATION_SLUG,
  TEST_QONTO_SECRET_KEY,
  TEST_QONTO_STAGING_TOKEN,
  TEST_NGROK_AUTH_TOKEN,
  TEST_AIRTABLE_API_KEY,
  TEST_AIRTABLE_BASE_ID,
  TEST_AIRTABLE_TABLE_1_ID,
  TEST_AIRTABLE_TABLE_2_ID,
} = process.env

if (!TEST_NOTION_TOKEN) throw new Error('TEST_NOTION_TOKEN env var is not defined')
if (!TEST_NOTION_TABLE_1_ID) throw new Error('TEST_NOTION_TABLE_1_ID env var is not defined')
if (!TEST_NOTION_TABLE_2_ID) throw new Error('TEST_NOTION_TABLE_2_ID env var is not defined')
if (!TEST_NOTION_TABLE_3_ID) throw new Error('TEST_NOTION_TABLE_3_ID env var is not defined')
if (!TEST_NOTION_TABLE_FILES_ID)
  throw new Error('TEST_NOTION_TABLE_FILES_ID env var is not defined')
if (!TEST_PAPPERS_API_KEY) throw new Error('TEST_PAPPERS_API_KEY env var is not defined')
if (!TEST_QONTO_ORGANISATION_SLUG)
  throw new Error('TEST_QONTO_ORGANISATION_SLUG env var is not defined')
if (!TEST_QONTO_SECRET_KEY) throw new Error('TEST_QONTO_SECRET_KEY env var is not defined')
if (!TEST_QONTO_STAGING_TOKEN) throw new Error('TEST_QONTO_STAGING_TOKEN env var is not defined')
if (!TEST_NGROK_AUTH_TOKEN) throw new Error('TEST_NGROK_AUTH_TOKEN env var is not defined')
if (!TEST_AIRTABLE_API_KEY) throw new Error('TEST_AIRTABLE_API_KEY env var is not defined')
if (!TEST_AIRTABLE_BASE_ID) throw new Error('TEST_AIRTABLE_BASE_ID env var is not defined')
if (!TEST_AIRTABLE_TABLE_1_ID) throw new Error('TEST_AIRTABLE_TABLE_1 env var is not defined')
if (!TEST_AIRTABLE_TABLE_2_ID) throw new Error('TEST_AIRTABLE_TABLE_2 env var is not defined')

const env = {
  TEST_NOTION_TOKEN,
  TEST_NOTION_TABLE_1_ID,
  TEST_NOTION_TABLE_2_ID,
  TEST_NOTION_TABLE_3_ID,
  TEST_NOTION_TABLE_FILES_ID,
  TEST_PAPPERS_API_KEY,
  TEST_QONTO_ORGANISATION_SLUG,
  TEST_QONTO_SECRET_KEY,
  TEST_QONTO_STAGING_TOKEN,
  TEST_NGROK_AUTH_TOKEN,
  TEST_AIRTABLE_API_KEY,
  TEST_AIRTABLE_BASE_ID,
  TEST_AIRTABLE_TABLE_1_ID,
  TEST_AIRTABLE_TABLE_2_ID,
}

export default env
